import type { Metadata } from "next";
import "@/app/globals.css";
import { currentUser } from "@clerk/nextjs/server";

import Link from "next/link";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function AdminLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const user = await currentUser();

	if (!user || user.publicMetadata.role !== "admin") {
		return (
			<div className="flex flex-col items-center justify-center h-screen">
				<p className="text-3xl font-semibold text-gray-800">
					You are not authorized to view this page
				</p>
				<Link className="text-blue-500 hover:underline" href="/">
					Go back to the home page
				</Link>
			</div>
		);
	}

	return <div>{children}</div>;
}
