import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";
import "@uploadthing/react/styles.css";
import {Analytics} from "@vercel/analytics/react";
import {SpeedInsights} from "@vercel/speed-insights/next"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Halo Health",
	description: "Generated by create next app",
	icons: "/fixedlogo.jpg",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
		<Analytics />
		<SpeedInsights/>
			<html lang="en">
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
				>
					{children}
					<Toaster />
				</body>
			</html>
		</ClerkProvider>
	);
}
